[package]
name = "zettlekasten"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blocking = "1.3.0"
reqwest = "0.11.14"
serde_json = "1.0.92"
url = "2.3.1"
